### ISSUE TITLE
attribute error ZED installation

### ISSUE THREAD

**Issue by BraedenCullenCodes** [stereolabs/zed-opencv#80]
Traceback (most recent call last):
  File "zed-opencv.py", line 178, in <module>
    main()
  File "zed-opencv.py", line 122, in main
    init.camera_resolution = sl.RESOLUTION.HD1080
  File "/usr/lib/python3.6/enum.py", line 326, in __getattr__
    raise AttributeError(name) from None
AttributeError: HD1080

I have no clue why it is throwing this error.

**Comment by Poutsh** [comment]
Hi @BraedenCullenCodes ,

Can you tell me which version of the ZED SDK are you using?

**Comment by BraedenCullenCodes** [comment]
resolved

**Comment by wxue1201** [comment]
how to solve the problem?
